### ISSUE TITLE
Rework SvnLogPage

### ISSUE THREAD

**Issue by cpwnd** [jlu-ilr-hydro/schwingbach#1]
Rework the SvnLogPage to displaying commits using the Github api

https://github.com/jlu-ilr-hydro/schwingbach/blob/d0485d271c2f7ffd62fbefb2107e98e2d6207fc0/webpage/pages.py#L744

**Comment by philippkraft** [comment]
Can be removed without Git-replacement

**Comment by cpwnd** [comment]
done
